name: resume_parser
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.0.1
  - transformers=4.30.2
  - pytorch=2.0.1
  - spacy=3.5.3
  - openai=1.3.0
  - pip
  - pip:
    - python-dateutil==2.8.2
